name: Backend build

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        working-directory: ./backend
        run: go build -v ./...

      - name: Test
        working-directory: ./backend
        run: go test -v ./...

      - name: gofmt check
        working-directory: ./backend
        run: bash -c 'if [[ "$(gofmt -l . | wc -l)" -gt 0 ]]; then echo Go formatting violations exist; exit 1; else echo Go formatting check passed ; fi'
