name: Check file headers

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: '1.27'
      - name: Install addlicense
        run: go install github.com/google/addlicense@latest
      - name: Check copyright headers
        run: find . -type f \( -name \*.ts -o -name \*.go \) -print0 | xargs -0 addlicense -check
